### ISSUE TITLE
Errno::EMFILE: Too many open files

### ISSUE THREAD

**Issue by wafendy** [grosser/parallel#113]
Hi,

I get this error intermittently, how do I ensure the files are closed?

Errno::EMFILE: Too many open files
/Users/william/.rvm/gems/ruby-2.1.2/gems/parallel-1.3.3/lib/parallel.rb:307:in `pipe'
/Users/william/.rvm/gems/ruby-2.1.2/gems/parallel-1.3.3/lib/parallel.rb:307:in `worker'
/Users/william/.rvm/gems/ruby-2.1.2/gems/parallel-1.3.3/lib/parallel.rb:297:in `block in create_workers'
/Users/william/.rvm/gems/ruby-2.1.2/gems/parallel-1.3.3/lib/parallel.rb:296:in `each'
/Users/william/.rvm/gems/ruby-2.1.2/gems/parallel-1.3.3/lib/parallel.rb:296:in `create_workers'
/Users/william/.rvm/gems/ruby-2.1.2/gems/parallel-1.3.3/lib/parallel.rb:253:in `work_in_processes'
/Users/william/.rvm/gems/ruby-2.1.2/gems/parallel-1.3.3/lib/parallel.rb:191:in `map'
/Users/william/.rvm/gems/ruby-2.1.2/gems/parallel-1.3.3/lib/parallel.rb:152:in `each'

**Comment by grosser** [comment]
hard to say, simple solution is raising the open-file limit ... if you cannot do that then you have to figure out where you are opening files and then make sure you close them
