### ISSUE TITLE
Question: Nesting supported?

### ISSUE THREAD

**Issue by mbj** [grosser/parallel#114]
Is nesting a parallel execution into another officially supported? I see some global state here: https://github.com/grosser/parallel/blob/master/lib/parallel.rb#L373 (instance variable of class singleton behaves like globally accessible mutable state under a scope).

Too me it looks like the internals could be confused when more than one parallel is active the same time. I have some evidence of this behavior in my mutant project.

As I need to switch away from parallel for other reasons (prepare for cross machine distribution) I did not reduced the problem yet and just start here with a question on the intentions of the project.

At the very least I think a note in the README could help to save some people debug time ;)

**Comment by grosser** [comment]
I think it works ... I never tried it though ... usually 1 level of parallel does the job :)
If you have some failing scenario we can investigate / turn them into failing tests ...

**Comment by mbj** [comment]
So I maybe found something that is out of spec. Thx for your reply. I'll close this issue now and come back with a reproduction the next time I hit this problem. Through this is unlikely to happen, as I only use parallel currently to get the amount of CPUs.

Do you consider to move the CPU detection into a separate gem?

**Comment by Daniel-ltw** [comment]
Nesting is not working for me. 

From a personal trial, it freezes after a single cycle at the first level. 

Could someone try replicating this and see what you get?

**Comment by grosser** [comment]
can you paste some reproduction steps ?

```
>> Parallel.map([[1,2,3], [4,5,6]]) {|x| Parallel.map(x){|i| "INNER #{i}"  } }
=> [["INNER 1", "INNER 2", "INNER 3"], ["INNER 4", "INNER 5", "INNER 6"]]
>>
```

**Comment by Daniel-ltw** [comment]
I tried doing with 

```ruby
Parallel.each_with_index([a,b,c]) do |x, index|
  retrieve_from_web(add)
  puts index
end

def retrieve_from_web(add)
  css = nokogiri_with_page_retrieval(add)
  Parallel.each_with_index(css.css('div.item')) do |item, index|
    process_item(item, index)
end
```

It is some what of this example.

**Comment by mbj** [comment]
The problem is that a small test will not be able to easily expose the problem.

The code I cited in the initial issue was affected by an easy to spot race on global data. And IMO no integration test can guarantee `parallel` is free of such race conditions.

**Comment by grosser** [comment]
Can you simplify to an example I can run in irb by pasting it ... Or a
failing test case ?
