### ISSUE TITLE
Modify outside variable inside Parallel.each

### ISSUE THREAD

**Issue by Ponf** [grosser/parallel#115]
Hi,
I want to run some hard calculations on different CPU cores and put result in some outside variable:

```ruby
extra = [].to_set
lock = Mutex.new
Parallel.each(someArray) { |item|
  lock.synchronize do
    extra.merge(some_calculation(item))
  end
}
if !extra.empty do
  #do something
end
```
but in this case if latest some_calculation returns null, extra will be empty. It looks like each process uses different extra instance. If I will use threads instead, extra will contain right values, but I will not get any benefits of different cores.

How to handle right such situation?

**Comment by grosser** [comment]
yes! :D
