### ISSUE TITLE
[Question] - Is there a way to stop the main process after sub-processes finish?

### ISSUE THREAD

**Issue by jessebs** [grosser/parallel#117]
It appears as though when I hit ctrl-c, any process that's currently running will stop mid-process.  Is there a way that I can wait for the sub-processes to finish before terminating?

**Comment by grosser** [comment]
Nope, the idea of ctrl+c support was that you want to get out 'now' so it should exit cleanly.
You might be able to overwrite the Interrupt handler and do something else ... or catch a different signal and cause it to raise Parallel:Break or something like that ...

**Comment by jessebs** [comment]
Thanks for the quick response.  

Catching the interrupt and raising a Parallel:Break didn't do the trick (it was one of the first things I tried).  Execution of each sub-process didn't complete.  I'll just design around it.

**Comment by martnst** [comment]
@jessebs Do you have any solutions or workarounds on this?

**Comment by jessebs** [comment]
This is probably not the answer you were hoping for, but we implemented our own solution instead of using parallel.

**Comment by grosser** [comment]
how about you share that solution :)
