### ISSUE TITLE
Parallel::Break and Parallel::Kill not caught when running on a platform without fork support

### ISSUE THREAD

**Issue by RJPercival** [grosser/parallel#128]
If running on a platform without fork support (e.g. Windows), and the default options are used (i.e. run in separate processes), Parallel#work_direct will be called. This method does not catch exceptions and pass them to Parallel#handle_exception, as Parallel#work_in_threads and Parallel#work_in_processes do. This results in the exception reached user code, which is not expected behaviour.

**Comment by grosser** [comment]
Yep sounds correct, can you fix it ?

**Comment by PyroSpirit** [comment]
Sure, I'll send a pull request shortly. I can't easily test it though, as the RSpec tests fail dramatically on Windows.
