### ISSUE TITLE
Parallel.map returns nil upon a Parallel::Break

### ISSUE THREAD

**Issue by philipmw** [grosser/parallel#142]
With the latest version of the gem, suppose you do this:

    results = Parallel.map([1, 2, 3], {in_threads: 2}) do |x|
      raise Parallel::Break
      x
    end

`results` is nil. I'd expect it to be a list, as `map` always returns a list.

Looking at the source code, it appears that `Parallel#handle_exception` intentionally returns `nil` instead of `results` on `Parallel::Break`... what's the reasoning for that?

**Comment by grosser** [comment]
```
>> [1,2,3].map{ break }
=> nil
```

**Comment by philipmw** [comment]
Hmm. Isn't `Parallel::Break` intended to signal that we want to stop processing data but keep the already-processed data? Throwing away everything we've already processed seems like a wrong way to go.

As a parallel (heh), the `concurrent-ruby` allows one to map over a list of futures using a custom thread pool executor. If the executor is shut down while mapping, then unprocessed items are simply nil, so a `.compact` on the output list returns the processed items.

**Comment by grosser** [comment]
you can return `Parallel::Stop` ... that should do what you want ... if not let's fix that ...

**Comment by grosser** [comment]
alternatively could use a producer/queue/lambda to stop producing items when xyz happens

**Comment by philipmw** [comment]
Good point, I didn't see the documentation for Parallel::Stop. Now I see it. Thanks.
