### ISSUE TITLE
No live threads left. Deadlock? (fatal)

### ISSUE THREAD

**Issue by StevenJL** [grosser/parallel#143]
I'm using this gem in a high traffic app.  It works 99.99% of the time but occasionally, I get these errors:

```
/usr/local/rvm/gems/ruby-2.1.2/gems/parallel-1.6.0/lib/parallel.rb:181:in `value': No live threads left. Deadlock? (fatal)
	from /usr/local/rvm/gems/ruby-2.1.2/gems/parallel-1.6.0/lib/parallel.rb:181:in `map!'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/parallel-1.6.0/lib/parallel.rb:181:in `in_threads'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/parallel-1.6.0/lib/parallel.rb:301:in `block in work_in_processes'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/parallel-1.6.0/lib/parallel.rb:140:in `kill_on_ctrl_c'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/parallel-1.6.0/lib/parallel.rb:300:in `work_in_processes'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/parallel-1.6.0/lib/parallel.rb:229:in `map'
```

Anyone seen them before? Anyone know why?

**Comment by grosser** [comment]
Never seen this one, sounds fun :(
Not even sure what causes this ... if you find out, please let me know!

**Comment by StevenJL** [comment]
@grosser 

I think I fixed it by changing `Parallel.map([])` to `Parallel.map([], in_threads: 5)`.  After that change I don't see those errors anymore.

I basically assumed that without that option, that it defaults to threads, but looking at the parallel code, I realized it defaults to processes.  So I explicitly use threads now and it seems to have fixed it.

The moral: don't assume :smile_cat:
