### ISSUE TITLE
in 1.3.3 lib/parallel.rb:162:in `map': uninitialized constant Module::Mutex (NameError)

### ISSUE THREAD

**Issue by alexharv074** [grosser/parallel#147]
Hi @grosser 

I found a bug affecting ruby 1.8.7 & your last 1.8.7 supported version parallel-1.3.3.

To fix I needed to build a new gem 1.3.3.1 and add 

    require 'thread'

in lib/parallel.rb

Is it possible for me to upload my patched 1.3.3.1 to rubygems.org?

**Comment by alexharv074** [comment]
(There didn't seem to be a 1.3 branch available to send you a pull request is all, being why I called it 1.3.3.1.)

**Comment by grosser** [comment]
I released a 1.3.3.1 ... since 1.3.3 is the last version not locked to ruby
1.9

could also require thread before requiring parallel :)

... and stop using unmaintained ruby versions :D

**Comment by alexharv074** [comment]
@grosser Thanks - much appreciated. :)
