### ISSUE TITLE
Scavenge workers after completing n jobs.

### ISSUE THREAD

**Issue by beekus** [grosser/parallel#148]
This is an excellent gem and I use it all the time. There is one use case where I have to hand roll my own solution though, and that is when I have jobs that use a good amount of memory. It would be awesome if there where an option to force each job to be worked by a newly forked worker instead of maintaining a worker pool.

**Comment by grosser** [comment]
Totally agree needed that a few times before too :)

Can you make that a PR ?

**Comment by beekus** [comment]
yeah it may take me a week or so to get it together with tests.

**Comment by grosser** [comment]
I already looked at that feature but did not find a easy way to add it ...
So good luck :)
