### ISSUE TITLE
Why Parallel.processor_count do not use standard Etc.nprocessors?

### ISSUE THREAD

**Issue by zekefast** [grosser/parallel#149]
There is a standard method in Ruby 2.2.0: [`Etc.nprocessors`](http://ruby-doc.org/stdlib-2.2.0/libdoc/etc/rdoc/Etc.html#method-c-nprocessors)

I think it would be better to rely on method from standard library instead of implemented it in system dependent way like done in [the code](https://github.com/grosser/parallel/blob/master/lib/parallel/processor_count.rb#L17]

What do you think?

Disclaimer: I have not tested all supported by `Parallel.processor_count` platforms to ensure that `Etc.nprocessors` behaves on them correctly.

**Comment by fenicks** [comment]
Etc.nprocessors might return a smaller number of cpus than physical number of cpus. The way `Parallel.processor_count` proceeds is a better approach ; no weird things are done. But we probably need both.

**Comment by grosser** [comment]
`The result might be smaller number than physical cpus especially when ruby process is bound to specific cpus. This is intended for getting better parallel processing.`

that sounds fine to me / like a feature ... can you make a PR to use it when it's available (`RUBY_VERSION > '2.2.0'`) ?

**Comment by zekefast** [comment]
@fenicks Thanks.
@grosser yes, I will try to submit it this weekend. Thanks!
