### ISSUE TITLE
Using parallel gem in testing environments blocks database connection

### ISSUE THREAD

**Issue by vinnyoodles** [grosser/parallel#152]
I made a [stackoverflow](http://stackoverflow.com/questions/34142886/using-parallel-gem-when-testing-activerecords-in-rails-application) question about this but got no response.

The parallel block works fine in the development database and it successfully connects with the right database, but in the testing environment, it has no access to any of the activerecords in the test database

the test block
```ruby
test 'importing game from confirmed list' do
  Nba::Game.create(stats_id: 1)
  Data::SportData::ProcessUpdate.new(season_id: 2015, league: 'nba').process_boxscores
end
```

the method using parallel
```ruby
def process_boxscores
   #Nba::Game.all = [#<Nba::Game id: 1, stats_id: 1, created_at: "2015-12-07 20:39:26", updated_at: "2015-12-07 20:39:26">]
   loaders = Parallel.map(list, in_threads: 4) {|game| 
     #Nba::Game.all = []
     build_boxscore_loader(game)
   }.compact
end
```

**Comment by grosser** [comment]
the test runs in a transaction, if you go to a new thread you are no longer in that transaction, so you don't see any of the temp records in that transaction

 - do not use transactions for this test (bad idea / most likely will pollute the test database)
 - produce data in the threads and leave the saving for the outside thread

**Comment by vinnyoodles** [comment]
@grosser Thanks, I'll try to figure how to set up this specific test case
