### ISSUE TITLE
queue interface

### ISSUE THREAD

**Issue by Try2Code** [grosser/parallel#156]
Hi!
I have a parallel queue implementation ready and in use for some years (https://github.com/Try2Code/jobQueue). Your gem offers more flexibility in terms of controlling the jobs and getting results back. So I started to port some of my scripts from jobQueue towards parallel. But large blocks do not seem to fit into the array-like approach of Parallel.map. Here, the queue works better for me.

My question is, if the queue-class could be integrated into the parallel gem? I prepared a possible change set here: https://github.com/Try2Code/parallel

cheers
ralf

**Comment by grosser** [comment]
let's take the discussion to the PR :)

https://github.com/grosser/parallel/pull/157
