### ISSUE TITLE
DeadWorker

### ISSUE THREAD

**Issue by ghazel** [grosser/parallel#160]
Nothing is printed by the workers.

```
/home/ec2-user/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:59:in `rescue in work': Parallel::DeadWorker (Parallel::DeadWorker)
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:56:in `work'
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:319:in `block (4 levels) in work_in_processes'
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:419:in `with_instrumentation'
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:318:in `block (3 levels) in work_in_processes'
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:312:in `loop'
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:312:in `block (2 levels) in work_in_processes'
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:183:in `block (2 levels) in in_threads'
```

Their code is:

``` ruby
Parallel.in_processes do
  loop do
    begin
      worker = Delayed::Worker.new
      worker.start
    rescue => e
      puts "worker failed: #{e.class}"
      puts e.backtrace
      sleep 1
    end
  end
end
```

Runs fine with `Parallel.in_threads`.

**Comment by grosser** [comment]
try `rescue Exception` ... maybe that catches more ...
also puts before / after the `worker.start` to maybe see weird behavior ...
this happens immediately or after a while ?
afaik this happens when the worker processes get killed ... any idea why that would happen ?

**Comment by ghazel** [comment]
Anything caught would be printed though, and nothing is printed.

**Comment by grosser** [comment]
Cannot help you debug without more info ...

**Comment by ghazel** [comment]
The problem happens immediately (well, after a weird ~15 second pause). Nothing external would be killing the workers.

**Comment by grosser** [comment]
did you try adding a puts at the start of the inner block ... does it even
reach there ?
does a empty in_processes block work ?

**Comment by ghazel** [comment]
I tried this:

```
    begin
      p "start #{Process.pid}"
      worker = Delayed::Worker.new
      p "mid #{Process.pid}"
      worker.start
      p "end #{Process.pid}"
    rescue => e
      p "exc #{Process.pid}"
      puts "worker failed: #{e.class}"
      puts e.backtrace
      sleep 1
    end
```

I only see:

```
"start 35615"
"start 35609"
"mid 35615"
"mid 35609"
/home/ec2-user/.rvm/gems/ruby-2.1.5/gems/parallel-1.6.1/lib/parallel.rb:59:in `rescue in work': Parallel::DeadWorker (Parallel::DeadWorker)
```

Total run time is about 23 seconds.

**Comment by grosser** [comment]
what happens if you use Process.wait fork { ... all this ... } ... does it
also break ?

**Comment by ghazel** [comment]
Ah yes, also breaks.

**Comment by grosser** [comment]
what is the backtrace ?
so it's not parallels fault / something is broken ?
ideally we can make parallel surface that error ...

**Comment by ghazel** [comment]
There's no backtrace. The child process just dies. Looking at `Process.wait2`, it seems:

`SIGABRT (signal 6) (core dumped)`

So, I have some sort of problem that crashes on fork, which I'll look into.

**Comment by pokrovskyy** [comment]
I stumbled upon the same issue and it turned out that OS was killing the worker processes because of intermittent high memory consumption bumps. So it killed some of the workers eg:

Nov 13 18:04:35 w3 kernel: Out of memory: Kill process 7873 (util.rb:24) score 55 or sacrifice child

Which resulted in Parallel::DeadWorker being raised. Although you said nothing normally should have killed the workers, it may have been the system which did that like in my case. Check your /var/log/messages for this case. Hope this helps someone.

**Comment by grosser** [comment]
nice digging! :D

**Comment by gjtorikian** [comment]
> Which resulted in Parallel::DeadWorker being raised. Although you said nothing normally should have killed the workers, it may have been the system which did that like in my case. Check your /var/log/messages for this case. Hope this helps someone.

I am from the future, and I thank you @pokrovskyy. This helped me debug my issue.

**Comment by grosser** [comment]
how is this covid thing going in the future ? :D
