### ISSUE TITLE
Cumulative sum question

### ISSUE THREAD

**Issue by dougsko** [grosser/parallel#162]
I'm having trouble getting a running summation working and I'm not sure what I'm doing wrong.  In the following example, why is ```parallel_sum``` always 0 and what's the right way to get this going? 

```ruby
# this works
sum = 0
(1..10).map{|x| sum += x}
puts "sum = #{sum}"

# this does not
parallel_sum = 0
Parallel.map((1..10), :in_processes => 2){|x| parallel_sum += x}
puts "parallel_sum = #{parallel_sum}"
```

Thanks!

**Comment by grosser** [comment]
processes have their own copies of variables and cannot talk back, you can only use the return value

```Ruby
Parallel.map((1..10), :in_processes => 2){|x| x }.sum
```
