### ISSUE TITLE
Sequel support

### ISSUE THREAD

**Issue by steakknife** [grosser/parallel#164]
Several issues encountered using Parallel with Sequel, support would be awesome for batch job (ETL-ish) type work:

- `Sequel.connect(..., single_threaded: false)` ->
    - `initialize': SQLite3::SQLException: no such table: {{tablename}} (Sequel::DatabaseError)`
- `Sequel.connect(..., single_threaded: true)` ->
    - `step': SQLite3::SQLException: cannot start a transaction within a transaction (Sequel::DatabaseError)`

See also: #135

**Comment by grosser** [comment]
PR welcome ... maybe start with a wiki page / tips section if it is not straight forward

**Comment by steakknife** [comment]
I have no idea how to fix it, it needs someone whom knows Parallel and Sequel internals.

**Comment by steakknife** [comment]
Added content to https://github.com/grosser/parallel/wiki/Sequel

**Comment by steakknife** [comment]
Not sure how to solve this, one unsatisfactory but working solution is to use a concurrent-ruby ThreadPoolExecutor pool, which works great on millions of items.
