### ISSUE TITLE
Rails.logger.tagged inside parallel block is ignored

### ISSUE THREAD

**Issue by palexvs** [grosser/parallel#173]
I have an issue with logging in Rails when I use parallel:

```
Rails.logger.tagged("some_id") do
  Parallel.each([1,2,3,4], in_threads: 2) do |i|
    Rails.logger.tagged("another_id") do
      Rails.logger.debug "Req: #{i}"
    end
  end
end
```

returns 
```
[another_id] Req: 1
[another_id] Req: 2
[another_id] Req: 3
[another_id] Req: 4
```

instead of 
```
[some_id] [another_id] Req: 1
[some_id] [another_id] Req: 2
[some_id] [another_id] Req: 3
[some_id] [another_id] Req: 4
```

**Comment by grosser** [comment]
`puts Rails.logger.method(:tagged).source_location` and see how tagged is defined ... smells like it's not threadsafe (needs to use Thread.current[:logger_tags][:tags] << tag` or something like that) ... if this is on latest rails, then open a bug ... if not then upgrade or monkey-patch it yourself ... but nothing parallel can fix for you ... please post the fix you come up with for future google spelunkers :)
