### ISSUE TITLE
Access progress bar in finish lambda

### ISSUE THREAD

**Issue by jimoleary** [grosser/parallel#176]
I'd like to be able to change the title in the finish callback.

This allows more feedback to the user, for exampkle:

```ruby
      i =0
      finish = lambda { |_, _, result, pbar|
        i+=1
        pbar.title="#{i.to_s.rjust(4,' ')} : #{result}"
      }
```

The following patch would allow access (while maintaining backward compatibility):

```
diff --git a/lib/parallel.rb b/lib/parallel.rb
index 020df18..130d77a 100644
--- a/lib/parallel.rb
+++ b/lib/parallel.rb
@@ -267,7 +267,13 @@ module Parallel
         progress = ProgressBar.create(progress_options)
         old_finish = options[:finish]
         options[:finish] = lambda do |item, i, result|
-          old_finish.call(item, i, result) if old_finish
+          if old_finish
+            if old_finish.arity == 4
+              old_finish.call(item, i, result, progress)
+            else
+              old_finish.call(item, i, result)
+            end
+          end
           progress.increment
         end
       end
```

Let me know if you would consider this change and I can send a pull request.

**Comment by grosser** [comment]
seems like a strange edge case and an additional complixity/runtime cost for everyone else, so I'd prefer not to have that ... you should be able to implement your own progress bar in a finish callback ... that might work well ...

**Comment by jimoleary** [comment]
I'm  not looking to use a different progress bar,  I just want to be able
to change the title on the current one to give more feedback.

It's not a huge deal as I  have monkey patched your version but that makes
my code more brittle.  However,  I can always pin the gem version to avoid
issues.

Feel free to close the issue.

Thanks.

**Comment by grosser** [comment]
I'm not suggesting to use a different one, but to use the same but with
your own configuration, since that might be cleaner then patching the gem

**Comment by jimoleary** [comment]
Looking at the code,  the progress bar is created inside the gem and after
the finish lambda is created.

So I  can't pass it in and don't see how I can get a reference to it. The
only thing I  can pass are the options which contain the initial title and
format etc.

As I  mentioned it's a small suggestion,  and not a deal breaker when I
take the 4x improvement in performance into account ;)
I'm not suggesting to use a different one, but to use the same but with
your own configuration, since that might be cleaner then patching the gem
On May 29, 2016 3:40 PM, "jimoleary" <notifications@github.com> wrote:

> I'm not looking to use a different progress bar, I just want to be able
> to change the title on the current one to give more feedback.
>
> It's not a huge deal as I have monkey patched your version but that makes
> my code more brittle. However, I can always pin the gem version to avoid
> issues.
>
> Feel free to close the issue.
>
> Thanks.
> On 29 May 2016 11:29 pm, "Michael Grosser" <notifications@github.com>
> wrote:
>
> > seems like a strange edge case and an additional complixity/runtime cost
> > for everyone else, so I'd prefer not to have that ... you should be able
> to
> > implement your own progress bar in a finish callback ... that might work
> > well ...
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/grosser/parallel/issues/176#issuecomment-222386568>,
> > or mute the thread
> > <
>
https://github.com/notifications/unsubscribe/AABX6td2ow6nu2PHpBqQv03TwJ0S7DA2ks5qGhNKgaJpZM4IpQk1
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/grosser/parallel/issues/176#issuecomment-222387131>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/AAAsZ15Jougz6l6socktoCmt9c9Ccnubks5qGhXkgaJpZM4IpQk1
>
> .
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/grosser/parallel/issues/176#issuecomment-222387186>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AABX6verZ1xicp38ldOkJdvBRBaWR5uNks5qGhZOgaJpZM4IpQk1>
.

**Comment by grosser** [comment]
all :progress option does is trigger the creation of a finish lambda, you
can create a custom progress bar and set it as finish lambda to do whatever
you please

**Comment by jimoleary** [comment]
You are 100% correct. That is a much simpler (or better) approach. I will change to do that instead.

Thanks!
