### ISSUE TITLE
Gem no longer installs for ruby 2.1.1

### ISSUE THREAD

**Issue by emlloyd** [grosser/parallel#181]
Please can you lock down the version of activerecord, so this gem continues to work with ruby 2.1.1.

gem install activerecord
ERROR:  Error installing activerecord:
    activesupport requires Ruby version >= 2.2.2.

**Comment by grosser** [comment]
how is `gem install activerecord` parallels problem ?

**Comment by ndbroadbent** [comment]
Haha yes, the `parallel` gem has literally zero dependencies.
