### ISSUE TITLE
Potential Tip

### ISSUE THREAD

**Issue by epugh** [grosser/parallel#182]
If you want to share a variable among the parallel processes, then make sure to use seperate threads, not seperate processes!

In my use case, I have a list of objects in an array called `opportunities`, each that needs additional data that I get by making an HTTP request.   If I don't specify `in_threads` then out of the scope of that Parallel block I lose my new data:

```ruby
    Parallel.each(opportunities, in_threads: 4) do |opportunity|
      puts "Loading touchpoints for opportunity #{opportunity.name} in slot #{Parallel.worker_number}"
      load_touchpoints(opportunity, jar)
    end
```

Took a bit of googling about, so maybe a Tip candidate?  If there are better ways of doing this, love to hear them!

**Comment by grosser** [comment]
Was already in the readme ... maybe this is easier to read ...

https://github.com/grosser/parallel/commit/6d646eda757fe5b64f7dd57851af0f95d4bd045d
