### ISSUE TITLE
what's the connection instance var for?

### ISSUE THREAD

**Issue by jjb** [grosser/parallel#193]
in this example:

```ruby
# maybe helps: reconnect once inside every fork
Parallel.each(User.all, in_processes: 8) do |user|
  @reconnected ||= User.connection.reconnect! || true
  user.update_attribute(:some_attribute, some_value)
end
```

What's the `@reconnected` instance var for? All forked processes will find it to be undefined, and it's not referenced again.

**Comment by grosser** [comment]
each fork works as a worker, so it will run the same block multiple times (16 with 8 workers = 2 items per worker) so it will only do the reconnect when processing the first item

**Comment by jjb** [comment]
ahhh. cool!
