### ISSUE TITLE
Anyway to capture the stdout of each process run?

### ISSUE THREAD

**Issue by AlexEvanczuk** [grosser/parallel#195]
```
results = Parallel.map(tasks_to_run) do |task_type|
   task_options = options[task_type]
   run_task(task_type, task_options, changed_files_only)
end
```

I have 4 or 5 tasks to run, and running in parallel really speeds things up.  However, the logging is interleaved.  Does parallel have any sort of functionality to pipe stdout from each process into its own string?

**Comment by grosser** [comment]
The only thing that works is capturing the output in the process and then making it part of the result.
(or writing it to a separate file per process and then concatting all these files)

```Ruby
Parallel.map([1,2,3,4]) do |i|
  `echo #{i}`
end
```

**Comment by AlexEvanczuk** [comment]
Hey --

Thanks -- I ended up doing something similar to this.  For anyone else trying to do this, here are two helpful functions to capture and chunk output in `Parallel`.

First convert any output from shell scripts to use STDOUT (note `puts` is shorthand for `STDOUT.puts` if you haven't modified your global `$stdout`).

I added these two functions to a logger class
```
    #
    # This converts shell output to stdout, which can be captured
    # for each iteration of Parallel
    #
    def self.execute_command_with_stdout(command)
      status = Open4.popen4(command) do |pid, stdin, stdout, stderr|
        puts stdout.read
        puts stderr.read
      end

      return status
    end
```

```
    #
    # Given a block, takes in all output to $stdout and $stderr from that block
    # and then returns the captured output along with the result of the block
    #
    def self.capture_stdout &block
      require "stringio"
      require 'ostruct'
      stdout, stderr = StringIO.new, StringIO.new
      $stdout, $stderr = stdout, stderr
      result = block.call
      log = [stdout.string, stderr.string].join("\n")
      [result, log]
    ensure
      # Restore the previous value of stdout
      $stdout = STDOUT
    end
```

Then tie it together:
```
task_results = Parallel.map(tasks_to_run) do |task|
  exit_status, log = capture_stdout do
    # DO THINGS HERE
  end
  Task.new(exit_status, log)
end
```

Take care,
Alex
