### ISSUE TITLE
the mutex params leak

### ISSUE THREAD

**Issue by luizamboni** [grosser/parallel#197]
```ruby
require "parallel"

options = { in_processes: 3 }

results = Parallel.map(['a','b','c'], options ) { |one_letter| 
  puts one_letter 
}

puts options.inspect
# {:in_processes=>3, :mutex=>#<Thread::Mutex:0x000000021781b0>, :return_results=>true}
```
the instance of mutex created in internals is exposed out scope of block, and remains end affect the perform of CG

this behavior can be avoided simple cloning the **options** params in begin

```ruby
2.4.0-rc1 :001 > a = {a: "a"} 
  => {:a=>"a"} 
2.4.0-rc1 :002 > b= a.clone
#  => {:a=>"a"} 
2.4.0-rc1 :003 > b[:c] = "c"
#  => "c" 
2.4.0-rc1 :004 > b
#  => {:a=>"a", :c=>"c"} 
2.4.0-rc1 :005 > a
#  => {:a=>"a"} 
2.4.0-rc1 :006 > b.object_id
#  => 14202320 
2.4.0-rc1 :007 > a.object_id
#  => 14220180 
```

**Comment by grosser** [comment]
sounds good, can you make a PR ?

**Comment by luizamboni** [comment]
of course, in this night, special thanks to my work friend [cacilhas ](https://github.com/cacilhas)to help me read  the source, and detect the
behavior

**Comment by grosser** [comment]
yeah these bugs are tricky to find ... if you find more let me know :D
