### ISSUE TITLE
Would be really handy to have more methods: `flat_map`, `reject`, `find`, `any?`, `all?`

### ISSUE THREAD

**Issue by ndbroadbent** [grosser/parallel#198]
I was also thinking about `reduce`, but I guess you couldn't share the accumulator variable across processes.

I've been trying to figure out how to implement `any?` and `all?` using `raise Parallel::Kill`, but it doesn't seem very efficient. Is there a better way to do the following?

```
        result = Parallel.map(array) do |item|
          unless condition(item)
            raise Parallel::Kill
          end
        end

        if result.nil?
          # at least one condition was false
        else
          # all conditions were true
        end
```

I don't really care about the result array (in this example it's just full of nils).

**Comment by grosser** [comment]
that looks about right ...
I think it would be neat to have them ... maybe use Break instead to avoid
killing things mid-process

**Comment by ndbroadbent** [comment]
Thanks for your reply! I've added a pull request for `any?` and `all?`. I'll have a go at some of the other ones, too.
