### ISSUE TITLE
Why values is not added to object

### ISSUE THREAD

**Issue by begin29** [grosser/parallel#208]
I can't recognize why values is not added to object process mode.  

https://pastebin.com/xS0fUTDD
`cont.blank? # true`

I checked there object_id outside Paralell block and inside and it is always the same in memory.

**Comment by grosser** [comment]
runs in multiple processes, so objects are not shared
options are:
 - use .map to return values
 - use `in_threads: 8` to share objects

**Comment by begin29** [comment]
yeah, but if I can see the same object with the same memory address why I can't write to that object from proceses and actually see result after forking?

**Comment by grosser** [comment]
copy-on-write ... in a fork the objects look the same, but when it's
written to a new memory copy is made ... just does not work ... basic ruby
foobar ... in other languages this might work if you have access to the
memory address ... but not in ruby
