### ISSUE TITLE
PG connect have been closed after run parallel.map

### ISSUE THREAD

**Issue by griffinqiu** [grosser/parallel#209]
My code example:

Parallel.map row_slice, 3 do |row|
... do something. Most of are mongo actions
end
PG.query  

The get blew error when I exec PG.query. It look like the PG connect have been closed. I saw the same issue https://github.com/grosser/parallel/issues/62. But that issue have been opened long time and no updates.

_ActiveRecord::StatementInvalid: PG::UnableToSend: SSL connection has been closed unexpectedly:_

**Comment by griffinqiu** [comment]
* rails (4.2.7.1)
 * pg (0.18.4)
 * parallel (1.6.1)

**Comment by grosser** [comment]
need to disconnect and then reconnect inside the block so it has it's own db connection

better keep the discussion on #62 so everyone gets updated

**Comment by griffinqiu** [comment]
@grosser Thank your for reply. But I feel unsure about there is no problem in most cases. Do you have more details for reason the problem?

**Comment by grosser** [comment]
The problem comes from the connection being shared between 2 processes, so
weird things can happen ... need to disconnect/reconnect so they do not
share the same connection.
