### ISSUE TITLE
Call Parallel tests from console to start the tests!

### ISSUE THREAD

**Issue by reach2jeyan** [grosser/parallel#210]
I know the question is very lame, but I have some rake tasks which are cucumber mobile tests with appium and I want this to run on different simulators parallely for test distribution

PFB the rake

```
def run_cucumber(cucumber_options)
  Cucumber::Rake::Task.new do |t|
    t.cucumber_opts = cucumber_options
  end
  Rake::Task[:cucumber].invoke
end

task :iphone_7 do |t|
  ENV["DEVICE"] = "iphone7"
  run_cucumber('-r features features/test.feature --format pretty --tags @slave1')
end

task :iphone_8 do |t|
  ENV["DEVICE"] = "iphone8"
  run_cucumber('-r features features/test.feature --format pretty --tags @slave2')
end

tasks = [:iphone_7,:iphone_8]
Parallel.map([tasks]) do |one_letter|
  puts one_letter
end
```
Now, I am not sure if this is the right way to put the tasks in an array and map it? Also, How do I start these rake tests in parallel? is there a command?

When I use rake parallel it builds the tests in sequence and not in parallel.

**Comment by thomasfedb** [comment]
Have a look at `Rake::MultiTask`, which might handle your usecase adequately.

**Comment by grosser** [comment]
MultiTask parallelizes using threads ... so not the same ...
```Ruby
Parallel.each([tasks]) do |task|
  Rake::Task[task].invoke
end
```
