### ISSUE TITLE
Tidy dependencies in Gemfile/Gemfile.lock/parallel.gemspec

### ISSUE THREAD

**Issue by cyclotron3k** [grosser/parallel#212]
`Gemfile` lists a few dependencies, which are not listed in `parallel.gemspec`, so they are not installed when you include `Parallel` in your project... but this is ok, because they are not actually dependencies. `Parallel` will run perfectly well without `active_supporter`, `mysql2`, `tzinfo`, etc. E.g. `mysql2` and `sqlite` aren't used anywhere in the gem.

Checking `Gemfile.lock` into source control is not recommended: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

Happy to make a PR.

**Comment by grosser** [comment]
No thanks :)
https://grosser.it/2015/08/14/check-in-your-gemfile-lock/

**Comment by cyclotron3k** [comment]
Ok no problem. I just realised that the unit tests use mysql and sqlite, etc.
