### ISSUE TITLE
Long pause before script throws me back to prompt

### ISSUE THREAD

**Issue by NorseGaud** [grosser/parallel#218]
Script has a puts "Script Started at the beginning, then the below .each, and ends (after the end of the Parallel.each) with a puts "Script Complete"

`Parallel.each(account_map_blocks, :in_threads => 5) do |map_block|`

The issue I'm seeing is that once the puts "Script Complete" happens, it sits there for a good 2 minutes before throwing me back into the Command Line so I can re-execute ruby script.rb

The Parallel.each just ends, I don't break or anything. 

Is this a potential wait to release memory? Or the thread to be cleaned up? Not sure where to even start with this. I'd love some help! Thanks!

**Comment by grosser** [comment]
can you paste a more complete example that I can paste into a test file to reproduce ?

```
require 'parallel'
puts "start"
Parallel.each([1,2,3,4], in_threads: 5) { puts "ITEM" }
puts "complete"
```

```
time ruby foo.rb
start
ITEM
ITEM
ITEM
ITEM
complete

real	0m0.282s
```

**Comment by NorseGaud** [comment]
I'm not sure I can unfortunately. I have some stuff making SDK calls to internal data services.
I do notice that if I try and Interrupt with ctrl+c while it's doing this pause at the end, I get

```
        12: from /usr/local/opt/gems/gems/theplatform-2.1.1/lib/theplatform/user.rb:43:in `block in initialize'
        11: from /usr/local/opt/gems/gems/theplatform-2.1.1/lib/theplatform/user.rb:82:in `sign_out'
        10: from /usr/local/opt/gems/gems/theplatform-2.1.1/lib/theplatform/services/web.rb:21:in `block in build_web_service_method'
         9: from /usr/local/opt/gems/gems/theplatform-2.1.1/lib/theplatform/services/web/methods.rb:46:in `post'
         8: from /usr/local/opt/gems/gems/excon-0.45.4/lib/excon/connection.rb:297:in `post'
         7: from /usr/local/opt/gems/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
         6: from /usr/local/opt/gems/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
         5: from /usr/local/opt/gems/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:6:in `response_call'
         4: from /usr/local/opt/gems/gems/excon-0.45.4/lib/excon/response.rb:53:in `parse'
         3: from /usr/local/opt/gems/gems/excon-0.45.4/lib/excon/socket.rb:44:in `readline'
         2: from /usr/local/opt/gems/gems/excon-0.45.4/lib/excon/socket.rb:48:in `rescue in readline'
         1: from /usr/local/opt/gems/gems/excon-0.45.4/lib/excon/socket.rb:295:in `timeout_reached'
/usr/local/opt/gems/gems/excon-0.45.4/lib/excon/socket.rb:295:in `select': Interrupt
```
 
Wonder if this is an excon socket being open that's keeping the threads held until they timeout (what throws me back to the CMD).

**Comment by grosser** [comment]
this might be a `at_exit` hook ... is it also slow to exit when not using parallel ?
you can override `at_exit` with some logging to find out who uses it

**Comment by NorseGaud** [comment]
You're right. I swear that I turned off parallel and couldn't replicate the exit delay. Ugh. Thanks for looking and getting me to a solution!
