### ISSUE TITLE
Parallel can not be used inside of ActiveRecord transaction

### ISSUE THREAD

**Issue by bogdan** [grosser/parallel#219]
Is there a way to deal with parallel call that doesn't do anything with ActiveRecord inside of ActiveRecord transaction without caring of the Activerecord
Consider the following scenario:

``` ruby
    ApplicationRecord.connection.reconnect!
    ApplicationRecord.transaction do
      User.first.touch
      Parallel.each([1,2]) do
        1
      end
      # ApplicationRecord.connection.reconnect!
    end
```

Currently it produces: 
ActiveRecord::StatementInvalid: Mysql2::Error: MySQL server has gone away

Uncommenting the connect silently erases the transaction and I am not able to run it again.

The plain `Thread` implementation however doesn't have any problems with ActiveRecord:

``` ruby
    ApplicationRecord.connection.reconnect!
    ApplicationRecord.transaction do
      User.first.touch
      2.times.map do
        Thread.new do
          1
        end
      end.map(&:join)
    end
```

**Comment by grosser** [comment]
that should work just fine, change it to `puts Parallel.map([1,2]) { |x| x }` and it should show the output

**Comment by grosser** [comment]
then try `fork { 111 }` and see if that causes the same error ... should definitely not reconnect
what line does the exception come from ?

**Comment by grosser** [comment]
works just fine on rails 5, there must be something else going on, try with a simpler app

```
ApplicationRecord.transaction do
  Link.first.touch
  Parallel.map([1,2]) do
    111
  end
end
   (0.2ms)  BEGIN
  Link Load (0.8ms)  SELECT  `links`.* FROM `links` ORDER BY `links`.`name` ASC LIMIT 1
  Link Update (0.3ms)  UPDATE `links` SET `updated_at` = '2018-04-29 15:40:00' WHERE `links`.`id` = 134
   (2.3ms)  COMMIT
=> [111, 111]
```

**Comment by bogdan** [comment]
You are right, there is no error on the fresh rails app. I am not sure I have a mental power to debug it because the issue is reproduced in 8 years old app with a ton of functionality including DB sharding which requires active record power hacking. I will just close this one and open a new one if I'll get a more accurate reproduce.
