### ISSUE TITLE
Locking variables outside of Parallel.map

### ISSUE THREAD

**Issue by mooreryan** [grosser/parallel#220]
This question is related to https://github.com/grosser/parallel/issues/115.

So looking here https://github.com/grosser/parallel/blob/fe6f49c5599bd9fa3ea3a8a5d883602f6128934d/lib/parallel.rb#L496

It seems that we don't have to worry about locking a variable that was defined outside of the `Parallel.map` block if I'm going to modify it within a `start` or `finish` lambda.

Also you've got these specs where you're adding to a `sum` variable... https://github.com/grosser/parallel/blob/master/spec/cases/progress_with_finish.rb, and this https://github.com/grosser/parallel/blob/fe6f49c5599bd9fa3ea3a8a5d883602f6128934d/spec/parallel_spec.rb#L558

Here's a silly example just to double check and make sure I'm understanding the code properly, if I do something like this:

```ruby
ary = []
data = [[1, 2], [10, 20]]

finish = lambda do |item, idx, result|
  ary.push result
end

Parallel.map(data, in_processes: 4, finish: finish) do |n1, n2|
  n1 + n2
end
```

I'll get `ary` being either `[3, 30]` or `[30, 3]` without having to worry about explicitly locking `ary` with a `Mutex` correct?

**Comment by grosser** [comment]
yes
also a mutex or locking would not even work since the work is being done in different processes.
... and ary == result in the example so it kind of defeats the purpose :)
