### ISSUE TITLE
Run Parallel rspec in docker container.

### ISSUE THREAD

**Issue by samirchian** [grosser/parallel#221]
got this error when I was trying to run in multi process. `8`
os = `linux`

` /gem_volume/gems/parallel-1.12.1/lib/parallel.rb:72:in` `load': undefined class/module Archive:: (ArgumentError)
	from /gem_volume/gems/parallel-1.12.1/lib/parallel.rb:72:in `work'
	from /gem_volume/gems/parallel-1.12.1/lib/parallel.rb:382:in `block (4 levels) in work_in_processes'
	from /gem_volume/gems/parallel-1.12.1/lib/parallel.rb:495:in `with_instrumentation'
	from /gem_volume/gems/parallel-1.12.1/lib/parallel.rb:381:in `block (3 levels) in work_in_processes'
	from /gem_volume/gems/parallel-1.12.1/lib/parallel.rb:369:in `loop'
	from /gem_volume/gems/parallel-1.12.1/lib/parallel.rb:369:in `block (2 levels) in work_in_processes'
	from /gem_volume/gems/parallel-1.12.1/lib/parallel.rb:206:in `block (2 levels) in in_threads'
`

**Comment by Daniel-ltw** [comment]
Could you check your code for `Archive::`?

**Comment by samirchian** [comment]
there is no `Archive::` in my code but there is one in `chromedriver-helper-1.2.0` that I am using not sure if this is related..

**Comment by Daniel-ltw** [comment]
@samirchian Could you do check if zip is installed on your docker container?

**Comment by samirchian** [comment]
yes it is installed `/usr/bin/zip`

**Comment by samirchian** [comment]
no it is not  `/usr/bin/which: no zip in ...`

**Comment by Daniel-ltw** [comment]
You might need to install zip in the docker container, so Archive::Zip could run.

**Comment by Daniel-ltw** [comment]
Depending on what docker image based you are using, the command to install zip on the operating system is different. Please do check that out.

**Comment by grosser** [comment]
... does the command work when not run in parallel ?
... does the command work when run with `in_processes: 0` ? (noop mode)

**Comment by samirchian** [comment]
it works with one process
