### ISSUE TITLE
Is it safe to use in_processes and in_threads at the same time?

### ISSUE THREAD

**Issue by letiesperon** [grosser/parallel#222]
Hi!

Is it ok if I do 
```
Parallel.map(Books.all, in_processes: 4, in_threads: 10) do |book|
   process_book(book)
end
```
Will that spawn 10 threads for each of the processes?

Thank you!

**Comment by grosser** [comment]
no, needs to blow up when both are set since that is not supported ...
nesting 2 calls might work though

**Comment by grosser** [comment]
how about a PR to blow up ? :)

**Comment by mahemoff** [comment]
Hopefully that does it.

I worked around it via nesting, as you suggested (the outer loop uses each_slice, so each process receives a list of items which it can then delegate to separate threads). I think it could be incorporated into the library without too much difficulty. I may look into it at some stage, time-permitting, but at least we have the double argument flagged for now.
