### ISSUE TITLE
Options are being modified by Parallel.map

### ISSUE THREAD

**Issue by Annih** [grosser/parallel#226]
As a user when I pass options to a method, I don't want them modified. This is currently not the case with `Parallel.map`

What do you think?

**Reproduction steps**

With `Parallel v1.12.1`
```ruby
require 'parallel'
::Parallel.map([], {}.freeze)
```
Here is the result:
> FrozenError (can't modify frozen Hash)

**faulty code**
- In `map` the `mutex` option is modified [here
](https://github.com/grosser/parallel/blob/v1.12.1/lib/parallel.rb#L235)
- In `map` the `return_results` option is modified [here](https://github.com/grosser/parallel/blob/v1.12.1/lib/parallel.rb#L256)
- In `add_progress_bar!` the `finish` option is modified [here](https://github.com/grosser/parallel/blob/v1.12.1/lib/parallel.rb#L303
)

**Suggested solutions:**
1. Trivial one, dup the given options
2. Use local variable when possible (`return_results` & `mutex`), and find another way to pass the `finish` lambda

**Comment by grosser** [comment]
yes! Please make a PR to fix :)
