### ISSUE TITLE
redundancy IO write?

### ISSUE THREAD

**Issue by tigerlei010** [grosser/parallel#229]
a script as following:
```ruby
#!/usr/bin/ruby

require 'parallel'

fo = File.open("run.log","w")
10.times { |i| fo.puts "#{i} Hello." }

a = [1,2,3,4,5,6,7,8,9,10] * 1
result = Parallel.map( a , in_processes: 0) do |i|
        sleep(0.5)
        i*i*i
end
result.each {|i| fo.puts "#{i}"}
fo.close
exit 0
```
it works OK  ,  but if change `in_processes: 0` to `in_processes: 5` or other number greater than 0 ,  run.log become dog's breakfast. there will be 60 lines "xx Hello" in the beginning, but ,actually ,there should be 10 lines.

my ruby is `ruby 2.0.0p645 (2015-04-13 revision 50299) [x86_64-linux]`

**Comment by grosser** [comment]
might get flushed multiple times ... try the same with just `fork` and you will get the same results ... so not a issue for this library
