### ISSUE TITLE
Add items while processing ?

### ISSUE THREAD

**Issue by grosser** [grosser/parallel#237]
I'm trying to do a task in Parallel to save time and I want to be able to add new items to the list (array) as I discover new ones.

I'm trying to do this, but it doesn't seem to add new elements to array that Parallel is working on.

```ruby
require 'parallel'
array = ['1','2','3','4','5']

Parallel.each_with_index(array) do |e, i|
  puts "Working on #{e} which is #{i + 1} in the list ..."
  array.push(rand(1..100).to_i)
end
```

Could you help me understand how to do this with Parallel?

**Comment by grosser** [comment]
Parallel forks when executing in processes, so pushing things into the`array` won't work since it's not shared between all workers.

When using threads this would work, but would still need "Produce" pattern see https://github.com/grosser/parallel#usage

There might be a way to make this pattern work for processes too, but that would be with the `finish` hook, which runs in the main process.

**Comment by nimeshnikum** [comment]
@grosser I just started using `parallel` and this was the first issue I encountered. Thanks to cover this too! :+1:
