### ISSUE TITLE
Parallel compatible with Sidekiq?

### ISSUE THREAD

**Issue by thbar** [grosser/parallel#260]
I'm thinking about using `Parallel.map` together with Sidekiq, to keep a way to work sequentially (à la Elixir, so to speak) while parallelizing things inside a given Sidekiq job.

I'm curious to know if it is supposed to be compatible at the moment (at least the `in_thread` variant, but why not the `in_processes` variant too!) ; in particular, what will happen in case of exceptions raised during processing, and what would happen if the parent thread (calling `Parallel.map`) is interrupted.

Did anyone experiment with this?

**Comment by grosser** [comment]
should all just work, open an issue if it does not :D

exceptions shut down all workkers and then get re-raised

if the parent thread is interrupted it should kill all it's workers

**Comment by thbar** [comment]
Excellent, thanks!
