### ISSUE TITLE
Extending array with parallel methods

### ISSUE THREAD

**Issue by mahemoff** [grosser/parallel#261]
This is a propposed feature to monkey-patch the standard Ruby Array class with parallel methods, e.g.  `[1,2,3].each_in_parallel { |i| puts i }`. I prefer this syntax as it's object-oriented and closer to the original array method.

Since it can be dangerous to extend standard library functions - and not something everyone wants - it could require an initial config call like `Parallel.extend_core`.

[Here is a basic implementation](https://gist.github.com/mahemoff/fde4c30ad9fb3036a348d0560722b395), happy to submit as a PR if it seems useful.

**Comment by grosser** [comment]
not really interested in that, I prefer to keep it simple/findable
