### ISSUE TITLE
Running two different functions in parallel 

### ISSUE THREAD

**Issue by echan00** [grosser/parallel#267]
My apologies for asking such a silly question. How do I run two different functions in parallel using this gem?

**Comment by grosser** [comment]
`Parallel.map([-> { f1}, -> { f2 }], &:call)`

**Comment by echan00** [comment]
Thanks @grosser for the tip. What if I am expecting the two functions to return objects?

```
temp, inc = Query_A(param1, param2)
temp1 = Query_B(param1, param2)
```

**Comment by grosser** [comment]
`(temp, inc), temp1= Parallel.map([-> { Query_A(param1, param2)}, -> { Query_B(param1) }], &:call)`

`

**Comment by echan00** [comment]
`(temp, inc), temp1, temp2= Parallel.map([-> { Query_A(param1, param2)}, -> { Query_B(param1) },  -> { Query_C(param1) }], &:call)`

@grosser  if I want to run three functions does this start two or three processes simultaneously?

**Comment by grosser** [comment]
depends on how many cpus you have
add `, in_processes: 3` to make it use 3 consistently

**Comment by echan00** [comment]
Okay thanks. The `&:call` is throwing me off.

Would I add it in the end like this?

`(temp, inc), temp1, temp2= Parallel.map([-> { Query_A(param1, param2)}, -> { Query_B(param1) }, -> { Query_C(param1) }], &:call, in_processes: 3)`

**Comment by grosser** [comment]
block always comes last
`(temp, inc), temp1, temp2= Parallel.map([-> { Query_A(param1, param2)}, -> { Query_B(param1) }, -> { Query_C(param1) }], in_processes: 3, &:call)`
