### ISSUE TITLE
Adding a hook for having just started a process? (making SimpleCov work)

### ISSUE THREAD

**Issue by robotdana** [grosser/parallel#275]
I recently added simplecov to my project, and found if i wanted simplecov to track what Parallel was doing I had to override the `Parallel.worker` method to inject SimpleCov.start and a unique command name.

I ended up adding this whole overridden method to my .simplecov file:
```ruby
module Parallel
   def self.worker(job_factory, options, &block)
     child_read, parent_write = IO.pipe
     parent_read, child_write = IO.pipe

     pid = Process.fork do
       self.worker_number = options[:worker_number]

       begin
         # here begins my additions
         SimpleCov.command_name "Parallel #{worker_number} #{Process.pid}"
         SimpleCov.start
         # here ends my additions

         options.delete(:started_workers).each(&:close_pipes)

         parent_write.close
         parent_read.close

         process_incoming_jobs(child_read, child_write, job_factory, options, &block)
       ensure
         child_read.close
         child_write.close
       end
     end

     child_read.close
     child_write.close

     Worker.new(parent_read, parent_write, pid)
   end
 end
```

I'd love a way to do this that was expected. (and I'd prefer that way be global rather than every `Parrallel.each` call.)

Do you have a preference/expectation for how one should do this? I'm happy to make a PR adding an option if you'd like 

Perhaps someone could have in their .simplecov something like
```ruby
Parallel.post_fork = -> { 
  SimpleCov.command_name "Parallel #{Process.pid}"
  SimpleCov.start
}
```
and we add `Parallel.post_fork&.call` in the Process.worker method where i added my code?

Thanks :)

**Comment by grosser** [comment]
I'd rather have the post_fork as an option if possible, there are already too many global things happening :)

As a workaround you can also do:

```ruby
Parallel.each([1,2,3,4], in_processes: 2) do |i|
  puts "hey" unless $process_initialized
  $process_initialized = true
end
```

... or
```ruby
cpus = 2
Parallel.each_with_index([1,2,3,4], in_processes: cpus) do |_, i|
  puts "hey" if i % cpus == 0
end
```


FYI try [single_cov](https://github.com/grosser/single_cov) and [forking-test-runner](https://github.com/grosser/forking_test_runner)

**Comment by robotdana** [comment]
I made a pr with simplecov instead, https://github.com/colszowka/simplecov/pull/881 i recommend using this if you're here from google.
