### ISSUE TITLE
[RFC] Missing Ruby dev dependencies causes builds to fail

### ISSUE THREAD

**Issue by maldoinc** [grosser/parallel#279]
Build failures often indicate a fault with the software being built such as compilation or test failures. However, there is a subset of build failures (called *environmental* or *non-verification failures*) that are not expected within a standard application development lifecycle, such as build configuration failures, dependency resolution failures, infrastructure failures, and so on.

**Problem:** One type of environmental failure is due to ruby gems not being built due to missing dependencies. In your project, we detected 8 failures of this type over the May-June timespan. For instance, we found that [Build #501](https://travis-ci.org/grosser/parallel/builds/699142850) did not pass due to the above issue.

**Solution:** We were able to repair this and similar failures by installing the development version of ruby alongside with required packages. Example changeset produced by our repair strategy is: 

```diff

before_install:
+    sudo apt-get update
+    sudo apt-get install -y build-essential ruby-dev libgmp-dev;
        
```
---
*Disclaimer:* I developed a tool that repairs environmental build failures and I am now evaluating its usefulness for open-source projects.

*Please up/downvote the issue to indicate whether you agree/disagree with the report and the proposed fix.*

**Comment by grosser** [comment]
the build is currently not broken, so I don't see the need for this
this tool would be great for ad-hoc recommendations after a build failed
