### ISSUE TITLE
Worker "hangs" when using mini_racer 0.3.x

### ISSUE THREAD

**Issue by tisba** [grosser/parallel#280]
Hey there 👋 

we are using the `parallel` gem and also the `mini_racer` project in our codebase. In a recent update to `mini_racer` we noticed that our test suite hangs for code that uses `Parallel.each` with `in_processes`.

I'm trying to figure out if this is a bug in parallel (not "releaseing" the worker) or if this is a problem introduced by `mini_racer` directly. Any hints are greatly appreciated to figure this out. I also opened an issue over at https://github.com/rubyjs/mini_racer/issues/170.

Here is a minimal script to reproduce the issue, which only seems to happen on linux (on macOS 10.14.6 I could not reproduce it):

```ruby
# frozen_string_literal: true

# Run with:
#   ruby script.rb

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "parallel", "1.19.2"

  # --> broken
  gem "mini_racer", "0.3.1"
  gem "libv8", "8.4.255.0"

  # --> works
  # gem "mini_racer", "0.2.15"
  # gem "libv8", "7.3.492.27.1"
end

MiniRacer::Context.new.dispose

Parallel.each([1], in_processes: 1) do |i|
  puts i
end

# we will not get here :(
puts "DONE!"
```

The interesting thing is, that I can CTRL-C the process and it continues normally. Using `Parallel.map` it produces the correct result. This makes be believe that while the new `mini_racer` version seems to trigger the problem, it could be originating with `parallel`.

**Comment by grosser** [comment]
sounds like something around catching at_exit ... check the diff of
mini_racer to see if that was touched

**Comment by tisba** [comment]
In the Ruby part there seems [not to be an `at_exit` handler](https://github.com/rubyjs/mini_racer/compare/v0.2.15...v0.3.1). But since `mini_racer` has a native extension and I have a hard time to follow, I'll try to ping the maintainer to follow this lead.

**Comment by tisba** [comment]
In the meantime: Is there a way to crank up verbosity or use a debug mode to figure out exactly in which state the forked worker is?

**Comment by grosser** [comment]
`bundle open parallel` and then add debugging info
otherwise you could start a thread that always prints to see who is still
alive

`Thread.new { loop { puts "HEY #{$$}"; sleep 2 } } `

**Comment by tisba** [comment]
I'm pretty certain at this point this is caused by `mini_racer`, so I'm closing this issue here. Thank you, @grosser!
