### ISSUE TITLE
Limit Max DB Connections in Threads

### ISSUE THREAD

**Issue by berniechiu** [grosser/parallel#289]
Hi all,

I wonder if it's possible to limit DB connections to `1` or same connection with thread without raising connection pool error which we mainly use for parallel HTTP requests but might cause extra connection leaks if we wrap something more than just HTTP connections.

Ex.
```ruby
class ExampleExecutor
  def self.process(url, shipment = nil)
    response = HTTParty.post(url)
    # Don't want this one to open new connection, it's ok to share with the top level DB connection
    shipment.touch if shipment
    response
  end
end



responses = Parallel.map([url1, url2, url3]) do |url|
  ExampleExecutor.process(url, shipment)
end
```

**Comment by grosser** [comment]
it's not ok to share the with the local connection, there are race conditions inside of AR / it's not threadsafe afaik
- return all the records that need to be touched and then do that after
- use a mutex to touch them
- use a co-processor thread that pops messages from a queue and then processes them always in the same thread

**Comment by berniechiu** [comment]
@grosser no problem, thanks for the suggestion
