### ISSUE TITLE
why `Parallel` consume more time

### ISSUE THREAD

**Issue by jstdoit** [grosser/parallel#290]
Hi, i'm confusing why it cost more time when I used `Parallel` to handle array. Below is my test code

```ruby
#!/usr/bin/env ruby

require 'parallel'
require 'benchmark'

arr = (1..100000).to_a

puts Benchmark.measure{
  results = Parallel.map(arr, in_threads: 30) do |item|
    item += 1
    item
  end
}

puts Benchmark.measure{
  results = arr.map{|i| i+=1; i}
}
```

after the run, i got result as follows, the result shows that `Parallel` way consume more time than normal `map` way:

```bash
0.083716   0.002371   0.086087 (  0.085244)
0.004945   0.000233   0.005178 (  0.005178)
```

please help me when CAN I use `Parallel` to improve the efficiency of handle arrays, thanks!

**Comment by jstdoit** [comment]
I gonna know, when `time-consuming` task in the block, I should use `Parallel`.

**Comment by grosser** [comment]
Yeah, spinning up threads takes time too :)
