### ISSUE TITLE
Support Ruby 3.0's Ractor / Reactor

### ISSUE THREAD

**Issue by rmondello** [grosser/parallel#298]
Ruby 3.0's Reactors seem powerful: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

It'd be neat, if possible, if one could use Parallel to use processes when running on Ruby 2.x and Reactors in Ruby 3.x. Could take some of the weight of parallelism using processes way down.

**Comment by grosser** [comment]
They are super alpha and fragile, so PR welcome if it's simple/opt-in but not if it requires a giant rewrite.

**Comment by grosser** [comment]
poked this a bit and you can't pass a block to a ractor, so best you can do is:
```ruby
Parallel.map [1,2,3], in_processes: 2 do |i|
  Ractor.new { sleep 2; receive * 2 }.send(i).take
end
```

(somehow ractors in threads don't work :/ )
... would be nice to have a wiki page for this to show some basic examples

**Comment by grosser** [comment]
also tried defining fake methods with the block and calling that, but got
```
 defined with an un-shareable Proc in a different Ractor
```

... so only thing that works afaik is sending the class+name of a method and arguments

so this style could work:

```ruby
class Foo
  def self.bar(i)
    # stuff
  end
end
Parallel.map [1,2,3], in_ractors: 2, ractor: [Foo, :bar]
```

**Comment by grosser** [comment]
1.22.0
