### ISSUE TITLE
No Database Connection inside Parallel?

### ISSUE THREAD

**Issue by NemyaNation** [grosser/parallel#302]
Am I missing something here, I've been pulling my hair for the past hour or so trying to get just a basic simplistic task working and I've been having problems left right and center.

Look at:

```
p "before: ", Portfolio.all.size
stats = Parallel.map([1]) do |prod|
  p "inside: ",Portfolio.all.size
end
```

this outputs:
```
"before: "
1
"inside: "
0
```

Is this normal behaviour?

Ruby: `ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]`
Rails: `Rails 6.0.3.7`
Parallel: `parallel (1.20.1)`
PostgreSQL: `12`

Also and any attempt to return within the block results in this error: ` error: {"type":"Parallel::DeadWorker","errors":"Parallel::DeadWorker",`

I'm setting this branch to the side and coming back to it later, because it seems there is no other alternative for parallel processing on Ruby (maintained anyway)

**Comment by grosser** [comment]
see https://github.com/grosser/parallel#activerecord

**Comment by NemyaNation** [comment]
1st test:
```
p "before: ", Portfolio.all.size
stats = Parallel.map([1]) do |prod|
  @reconnected ||= Portfolio.connection.reconnect! || true
  p "inside: ",Portfolio.all.size
end
```
**same result**

2nd Test:
```
p "before: ", Portfolio.all.size
stats = Parallel.map([1]) do |prod|
  p "inside: ",Portfolio.all.size
end
Portfolio.connection.reconnect!
```
** same result **

3rd Test:
```
p "before: ", Portfolio.all.size
stats = Parallel.map([1]) do |prod|
  ActiveRecord::Base.connection_pool.with_connection do
    p "inside: ",Portfolio.all.size
  end
end
```
** same result **

Please re-open this issue.

**Comment by grosser** [comment]
you should not return in the block, but use `next result` if you want to short-circuit it
otherwise the block will stop and then you get the dead worker ... lmk if that works

**Comment by grosser** [comment]
and try with `in_processes: 0` so it does not do any forking, if that also fails then it's not the parallelization

**Comment by NemyaNation** [comment]
@grosser with `in_processes: 0` outputs correctly (so it's definitely parallelization):
```
"before: "
1
"inside: "
1
```

---
in the examples above I'm not returning anything, I just want to get simple parallelization to work with a connection to my db.

But since we're on that momentarily, how would one process a function depending on different inputs and get the response of those calculations?

for example a function
```
def findSquare(value)
  // code to find the square root
end

square_roots = Parallel.map(array) do |value|
  findSquare(value)
end
```
would square_roots contain the square roots of the array input?

**Comment by grosser** [comment]
yep, that's how it works

**Comment by grosser** [comment]
try disconnect before going into parallel, maybe that helps

**Comment by grosser** [comment]
... are you maybe in test mode and have a transaction open ?
dump the open transaction count

**Comment by NemyaNation** [comment]
@grosser what do you mean disconnect? how?

and also yes I'm testing this via an RSPEC (if that's what you mean by test-mode)

**Comment by NemyaNation** [comment]
Adding this before the Parallel block 
```
ActiveRecord::Base.connection_pool.disconnect!
```
results in the same output?

**Comment by grosser** [comment]
ah yeah it won't work during testing since that has an open transaction,
so any new connection will not see what is in that open transaction
fixtures might still work

**Comment by NemyaNation** [comment]
@grosser placed the code block in my original example inside a function and executed that function inside a rails console linked to the development environment instead and retrieved the correct output:
```
   (0.6ms)  SELECT COUNT(*) FROM "portfolios"
"before: "
1
   (0.5ms)  SELECT COUNT(*) FROM "portfolios"
"inside: "
1
```

and I removed all the suggestions you recommended above, so now the block is just:
```
stats = Parallel.map([1]) do |prod|
  p "inside: ",Portfolio.all.size
end
```
which leads me to believe it's definitely something with my test environment configuration.

**Comment by NemyaNation** [comment]
@grosser 

adding this into my RSPEC configuration allows it to work:

```
use_transactional_fixtures = false
```
