### ISSUE TITLE
1.20.2 yanked?

### ISSUE THREAD

**Issue by MrJoy** [grosser/parallel#304]
I see that 1.20.2 was yanked from Rubygems, and looking at the diff I don't really see an obvious reason as to _why_ it might need to have been yanked.  Could you outline what went wrong that resulted in the need to yank this?

**Comment by grosser** [comment]
change had to be reverted because it broke other peoples stuff https://github.com/grosser/parallel/pull/301

**Comment by grosser** [comment]
@pamgluss-slack @pedromartinez can tell you more / hopefully have and idea if this is good as is or should be moved forward again ... I could not reproduce either of their issues 🤷

**Comment by MrJoy** [comment]
Ahhhhh, I see what happened, and why the code misbehaved!

https://github.com/grosser/parallel/pull/299/files

Note the trailing comma on the `when` line.  That's going to basically make Ruby read the code like so:

```ruby
ppc = case RbConfig::CONFIG["target_os"]
        when /darwin[12]/, IO.popen("/usr/sbin/sysctl -n hw.physicalcpu").read.to_i
          # empty block
        when /linux/
           cores = {}  # unique physical ID / core ID combinations
```

So it will _always_ execute `/usr/sbin/sysctl -n hw.physicalcpu`, no matter what system you're on.  If `/usr/sbin/sysctl` isn't present, then `IO.popen` raises an error.  If it _does_ exist, then the output is read, and converted to an integer and used as a test value for whether that `when` block matches `RbConfig::CONFIG["target_os"]` -- which is probably never gonna happen, obviously.

**Comment by grosser** [comment]
oh wow 🤦 totally missed that ... 🎉

**Comment by grosser** [comment]
... rubocop would have found that 😞

**Comment by grosser** [comment]
welp rubocop does not care either ...

**Comment by grosser** [comment]
1.21.0

**Comment by MrJoy** [comment]
Many eyes make all bugs shallow.  Happy I could be of assistance, and thank you for your prompt response!
