### ISSUE TITLE
[Feature Request] Need access to the progress bar object

### ISSUE THREAD

**Issue by dwery** [grosser/parallel#315]
... to be able to call progress.log from within the block

**Comment by grosser** [comment]
Yeah I ran into that too ... if you have a good idea of how to make that work without adding lots of hackery 🤷 
... afaik create the progress bar outside and then you can call log on it all you want

**Comment by dwery** [comment]
I gave a quick look at the code, indeed it wouldn't fit very well. Seems reasonable to create it outside of Parallel.
