### ISSUE TITLE
Process.fork is not supported by this Ruby

### ISSUE THREAD

**Issue by enumag** [grosser/parallel#318]
Hello. I wanted to use the parallel gem but I'm getting this error. What's going on and how can I fix it please?

**Comment by grosser** [comment]
need to use threads if fork is not supported
you can use threads to spam processes
```
Parallel.in_threads(4) do
  `echo hey`
end
```

**Comment by enumag** [comment]
Unfortunately I don't think threads will work in my case. I need to do some work in separate process.

**Comment by grosser** [comment]
then chose a different ruby or make your threads fork as I showed
... can also try ractors, see https://github.com/grosser/parallel/pull/317 but that's pretty risky/new

**Comment by enumag** [comment]
Does these ractors work on Windows?

**Comment by grosser** [comment]
yeah on ruby 3.0+
... doubt it works on jruby, so not really an option for you afaik

**Comment by enumag** [comment]
Sorry but I'm a newbie. I don’t even know what jruby is. If I'm somehow using it then I'm not aware of it.

**Comment by grosser** [comment]
ah yeah, fork does not work on windows
