### ISSUE TITLE
What is the recomended way to implement a semaphore or lock using this library?

### ISSUE THREAD

**Issue by yeikel** [grosser/parallel#319]
Hi all, 

I am currently calling the library using the following code : 

```
 Parallel.map(..., in_processes: in_processes) do |item|
   step 1
   step 2
    step 3
```

The challenge is that step 3 involves making an api call that is rate limited 

Is there any recommended way to implement a semaphore (or some sort of lock) using this library? 

Or should I use a third party library? 

Thank you!

**Comment by grosser** [comment]
for processes you can only do file lock afaik `File.flock`
... for threads you could use a mutex (for api calls threads should be god enough)
