### ISSUE TITLE
Parallel causes a net slowdown

### ISSUE THREAD

**Issue by michaeleisel** [grosser/parallel#323]
In my case, I need to parse some large JSON files, and I find that doing it with `parallel` is actually slower than just doing it single-threaded. Cases:
```
files.map { |file| Oj.load_file(file) }
```
24.8 seconds
```
Parallel.map(files, processes: 1) { |file| Oj.load_file(file) }
```
134.0 seconds
```
Parallel.map(files, processes: 4) { |file| Oj.load_file(file) }
```
149.1 seconds

For other tasks I also see a similar slowdown. I'm on an M1 Macbook Pro, and I wonder if the processes being spawned by `parallel` use a lower quality-of-service or something.

**Comment by michaeleisel** [comment]
With `.each`, on a subset of those JSON files (16 files) and after running repeatedly to warm the caches, I get 2.8 seconds with normal serial execution and 3.6 seconds with `parallel`. So, the difference is not as drastic but still there. With ractors, I see similar decreased performance.

**Comment by grosser** [comment]
the only thing I could imagine doing that is disk io ...
maybe read the files into memory first and then start the blocks ?
(also make sure to return nil or the count from the blocks just in case)

**Comment by reitzig** [comment]
For spinning disks, random access is relatively slower compared to linear scan. You are converting N linear scans into random access patterns across the same data volume by parallelizing.
Not sure if it's the same for SSDs, but any form of caching the hardware or OS do will be similarly affected.

**Comment by michaeleisel** [comment]
I wonder if we could improve this by improving serialization speed when consolidating the objects produced by child processes by `.map`?
