### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by tigflanker** [grosser/parallel#327]
![微信截图_20220819094045](https://user-images.githubusercontent.com/22868157/185524434-de97e737-5967-4083-bf4d-1ba68fc472b5.png)
Parallel is very useful and powerful. But sometime it occur “ZeroDivisionError”, but actually i didn't have make any divide operation. 
Rerun, it will be OK.

**Comment by grosser** [comment]
this is a ruby repo
