### ISSUE TITLE
parallel groupby

### ISSUE THREAD

**Issue by tveinot** [grosser/parallel#334]
When I run results = df1.groupby(by=['Year'])['Time'].rolling(1).parallel_apply(sum) the resulting dataframe only has a 2 unnamed columns, a Time column with the same amount of records as what went in. I'm likely not using it right, all of the examples of using group_by with pandarallel just show df1 = df.groupby(column1).column2.rolling(n).parallel_apply(func), is there usage examples that outline stringing this together?

**Comment by grosser** [comment]
wrong language, this is ruby
