### ISSUE TITLE
Ruby 3.5 to drop `win32ole`

### ISSUE THREAD

**Issue by Earlopain** [grosser/parallel#345]
Ruby is continuing its path of requiring more gems to be specified. `win32ole` is next on the list (among others) and will start warning in Ruby 3.4: https://github.com/ruby/ruby/commit/f365bef0c78085b7db9b6736ae59c1657baa79a3

Usage is here, to get the number of cores on windows: https://github.com/grosser/parallel/blob/f66f10552e32681bf47f7dfd2f8183d7e0de442e/lib/parallel.rb#L331-L336

Something like the following may be a suitable replacement:
```rb
IO.popen("wmic cpu get NumberOfCores", &:read).scan(/\d+/).map(&:to_i).reduce(:+)
```

Output of that command:
`NumberOfCores  \n\n4              \n\n\n\n`

I have also openend the same report on `concurrent-ruby` at https://github.com/ruby-concurrency/concurrent-ruby/issues/1048 if you are interested. Both implementations for this are basically the same.

**Comment by grosser** [comment]
awesome, thx for the heads up!

**Comment by Earlopain** [comment]
I openend https://github.com/ruby-concurrency/concurrent-ruby/pull/1051 if you have some feedback
