### ISSUE TITLE
compatibility with ruby-progressbar (and csv)

### ISSUE THREAD

**Issue by dorianmariecom** [grosser/parallel#352]
```
require 'parallel'; require 'ruby-progressbar'; progress_bar = ProgressBar.create; Parallel.each(1..100) { |i| sleep(rand(2)); progress_bar.increment }
```

https://github.com/user-attachments/assets/278ed85c-caf3-42c3-9535-b7dde454e383

![Screenshot 2024-09-01 at 13 29 49](https://github.com/user-attachments/assets/bf99ad6a-16e9-4ecb-aa53-5695b12cd53f)

![Screenshot 2024-09-01 at 13 32 21](https://github.com/user-attachments/assets/0ae8989a-0f2f-437d-8c60-08a5c4a11850)

I also posted on ruby-progressbar repository https://github.com/jfelchner/ruby-progressbar/issues/196

I have some issues with csv as well, so I was thinking maybe it's something from parallel

**Comment by dorianmariecom** [comment]
```
>> require 'csv'; require 'parallel'; CSV.generate { |csv| Parallel.each([1, 2, 3]) { |element| csv << [element] } }
=> ""
```

**Comment by dorianmariecom** [comment]
works with threads, not with processes

**Comment by grosser** [comment]
Can't possibly work with processes since they are not connected to each other, but forked.
To make this work either:
- `Parallel.map(1..50, progress: "Doing stuff") { sleep 1 }`
- `Parallel.map(1..100, finish: -> (item, i, result) { ... progress bar stuff ... }) { sleep 1 }`

**Comment by dorianmariecom** [comment]
thanks @grosser, that works for the progress bar, but not for the csv :(

is there any way to run csv generation in parallel?

also didn't know parallel had a progress bar built-in, that's nice

**Comment by grosser** [comment]
You can generate CVS in each process, either return them or write to
separate files on disc, and then combine them after everything is done.

**Comment by dorianmariecom** [comment]
thanks, really smart by the way

i did this:

```
        result = headers_of(content) ? headers_of(content).to_csv : ""

        result + map(content) do |element|
          CSV.generate(headers: headers_of(content)) do |csv|
            csv << wrap(element)
          end
        end.join
```
